services:
  database:
    image: mysql:8.4
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env.docker
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
        
volumes:
  mysql_data:
